# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'dockerhub'
  imageRepository: 'joanjoho/ado-demo-app'
  dockerId: 'joanjoho'
  pswd: 'Abcde12345'
  containerRegistry: 'registry.hub.docker.com'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'docker-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: RepoScan
  displayName: Repo Scanning stage
  jobs:
  - job: RepoScan
    displayName: Scanning Github Repo
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
      displayName: 'Install Python 3.8'
    - script: pip install checkov
      displayName: 'Install Checkov'
    - script: checkov -d . --use-enforcement-rules --bc-api-key ce4c6ed8-0de2-4ed2-9eec-9d3ab88c5346::YQs74YXzN9wKdmJdV4zkZFgC10g= --repo-id billhoph/pipelines-javascript-docker --branch main -o cli -o junitxml --output-file-path console,CheckovReport.xml 
      displayName: 'Scan with Prisma Cloud'
      env:
        PRISMA_API_URL: https://api.prismacloud.io
      continueOnError: true
    - task: PublishTestResults@2
      inputs:
        testRunTitle: "Checkov Results"
        failTaskOnFailedTests: false
        testResultsFormat: "JUnit"
        testResultsFiles: "CheckovReport.xml"
        searchFolder: "$(System.DefaultWorkingDirectory)"
      displayName: "Publish > Checkov scan results"

- stage: Build
  displayName: Build stage
  dependsOn: RepoScan
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    - upload: manifests
      artifact: manifests

- stage: UnitTest
  displayName: Unit Test
  dependsOn: Build
  jobs:
  - job: UnitTest
    displayName: Performing Unit Test On Built Artifact
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
      displayName: 'Install Python 3.8'

- stage: ImageScan
  displayName: Image Scanning stage
  dependsOn: UnitTest
  jobs:
  - job: ImageScan
    displayName: Image Scanning stage
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: docker login -u $(dockerId) -p $(pswd) $(containerRegistry)
      displayName: 'Docker Login Harbor'
    - script: docker pull $(containerRegistry)/$(imageRepository):$(tag)
      displayName: 'Docker Pull Image'
    - task: prisma-cloud-compute-scan@3
      displayName: 'Container Image Scanning'
      continueOnError: true
      inputs:
        scanType: images
        twistlockService: 'prisma-cloud-demo'
        artifact: $(containerRegistry)/$(imageRepository):$(tag)

- stage: Deploy
  displayName: Deploy stage
  dependsOn: ImageScan

  jobs:
  - job: Deployment
    displayName: Application Deployment
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
      displayName: 'Install Python 3.8'
