apiVersion : apps/v1
kind: Deployment
metadata:
  name: ado-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ado-demo-app
  template:
    metadata:
      labels:
        app: ado-demo-app 
    spec:
      containers:
        - name: ado-demo-app 
          image: harbor.alson.space/demo/ado-demo-app
          ports:
          - containerPort: 8080
